### ISSUE TITLE
will it update 

### ISSUE THREAD

**Issue by zgy-daodaodao** [DrDonk/esxi-unlocker#1]

**Comment by DrDonk** [comment]
Sorry not sure what you mean. Can you give me some more details please?

**Comment by zgy-daodaodao** [comment]
vmware ESXi 7 udate 2  a, the newest version that vmware has released, is it support this platform

**Comment by DrDonk** [comment]
Yes it does work but I am still testing and so not released yet.

**Comment by DrDonk** [comment]
FYI I have been given a report that ESXi may experience VMFS issues with this code and so I am probably going to stop development on it.
