### ISSUE TITLE
Some of VMs can't boot after unlock

### ISSUE THREAD

**Issue by dateno1** [DrDonk/esxi-unlocker#13]
Host
CPU : i5-10600
RAM : 32G*4 (128G)
Disk : Intel P3600 2T (Dell OEM) + SATA SSD (for ESXI)
Version : ESXi-7.0U3g-20328353-standard
Unlocker Version : 4.0.3

All work well before patch but some of VMs can't boot after patch

relock and reboot all work well

sorry i was forgot error message (look like 'turn on VM on dissconnected VMFS')

**Comment by DrDonk** [comment]
Are you using vSphere to control the ESXi system? If the ESXi host has rebooted you need to right click on host in vCenter web app and reconnect the host.

**Comment by dateno1** [comment]
It connected on VCSA 

But boot failed on host (not VCSA)

Also failed VMs is not Mac (Windows 10 x64 installed)

**Comment by DrDonk** [comment]
Not sure what to do as I’ve never seen or had a report of an issue like this before. Can you run the following commands and attach the output please?

esxcli system visorfs tardisk list

and from unlocker:

check

**Comment by dateno1** [comment]
Now unlocker is removed (check result is not found)

```
sh check
VMware ESXi Unlocker 4.0.3
==========================
(c) 2011-2022 David Parsons

Checking unlocker...
Current version of ESXi: VMware ESXi 7.0.3 build-20328353
cat: can't open '/etc/unlock.conf': No such file or directory
Patch built for ESXi:
>>> ERROR: Mis-matched files please relock/unlock to update patches <<<
```

When it Installed : current&result version is same
-----------------------------
Current state (relocked)
```
esxcli system visorfs tardisk list
Tardisk Name  System         Size
------------  ------  -----------
vmx.v00         true  125273192 B
vim.v00         true  167048568 B
tpm.v00         true      24430 B
sb.v00          true  222130535 B
s.v00           true  140552711 B
atlantic.v00    true    1448856 B
bnxtnet.v00     true     941624 B
bnxtroce.v00    true     414352 B
brcmfcoe.v00    true    2280600 B
elxiscsi.v00    true     578872 B
elxnet.v00      true     651168 B
i40en.v00       true     842512 B
iavmd.v00       true     760440 B
icen.v00        true    2109032 B
igbn.v00        true     331776 B
ionic_en.v00    true     458672 B
irdman.v00      true     605600 B
iser.v00        true     278224 B
ixgben.v00      true     545424 B
lpfc.v00        true    3081728 B
lpnic.v00       true     651168 B
lsi_mr3.v00     true     360792 B
lsi_msgp.v00    true     494440 B
lsi_msgp.v01    true     683584 B
lsi_msgp.v02    true     530192 B
mtip32xx.v00    true     258128 B
ne1000_i.v00    true     648261 B
ne1000.v00      true     653232 B
nenic.v00       true     277200 B
nfnic.v00       true     625976 B
nhpsa.v00       true     710968 B
nmlx4_co.v00    true     799544 B
nmlx4_en.v00    true     728912 B
nmlx4_rd.v00    true     346624 B
nmlx5_co.v00    true    2742616 B
nmlx5_rd.v00    true     296920 B
ntg3.v00        true     122640 B
nvme_pci.v00    true     132184 B
nvmerdma.v00    true     182656 B
nvmetcp.v00     true     197168 B
nvmxnet3.v00    true     202224 B
nvmxnet3.v01    true     172752 B
pvscsi.v00      true     123024 B
qcnic.v00       true     305264 B
qedentv.v00     true    3829936 B
qedrntv.v00     true    3251160 B
qfle3.v00       true    3163024 B
qfle3f.v00      true    1402472 B
qfle3i.v00      true     378168 B
qflge.v00       true     510872 B
rste.v00        true     845016 B
sfvmk.v00       true     906720 B
smartpqi.v00    true     697664 B
vmkata.v00      true     207744 B
vmkfcoe.v00     true    1030744 B
vmkusb_n.v00    true    1183304 B
vmkusb.v00      true    1130000 B
vmw_ahci.v00    true     240488 B
bmcal.v00       true      78584 B
crx.v00         true   37525496 B
elx_esx_.v00    true    2372632 B
btldr.v00       true    1451025 B
esx_dvfi.v00    true     537077 B
esx_ui.v00      true   23185125 B
esxupdt.v00     true    2347379 B
tpmesxup.v00    true       9123 B
weaselin.v00    true    2765880 B
esxio_co.v00    true     518240 B
loadesx.v00     true    3672780 B
lsuv2_hp.v00    true      72432 B
lsuv2_in.v00    true      77296 B
lsuv2_ls.v00    true    1178032 B
lsuv2_nv.v00    true      14160 B
lsuv2_oe.v00    true      14168 B
lsuv2_oe.v01    true      14152 B
lsuv2_oe.v02    true      14160 B
lsuv2_sm.v00    true      55480 B
native_m.v00    true    2425417 B
qlnative.v00    true    2906168 B
trx.v00         true   15024679 B
vdfs.v00        true   14006029 B
vmware_e.v00    true     203840 B
vsan.v00        true   42465448 B
vsanheal.v00    true    8556718 B
vsanmgmt.v00    true   27537960 B
xorg.v00        true    3506401 B
gc.v00          true      60580 B
imgdb.tgz       true    1843200 B
basemisc.tgz    true   11714560 B
state.tgz       true     129536 B

```
--------------------
When unlocker is installed some of Windows 10 VM is OK but some of them is not OK (Can't power on)

**Comment by DrDonk** [comment]
Sorry I am really stumped here. I can't think what may be causing this to happen or where to look for clues. There's likely a log somewhere with details but I will have to see which one it is.

**Comment by dateno1** [comment]
I will re-test it at next host reboot

Which log do you need?

**Comment by S474N** [comment]
I have problem with booting ESXi host. 

```
PatchVMKCTL 4.0.3
=================
(c) 2014-2022 David Parsons

Filename: ./tmp/lib64/libvmkctl.so
Traceback (most recent call last):
  File "./patchvmkctl", line 96, in <module>
    main()
  File "./patchvmkctl", line 81, in main
    f(filename)
  File "./patchvmkctl", line 41, in patchvmkctl
    f.seek(applesmc)
OSError: [Errno 22] Invalid argument
Building apple.v00 VMTAR file...
Cleaning up tmp files...
Adding to bootbank...
Acquiring lock /tmp/bootbank.lck
Copying apple.v00 to /bootbank/apple.v00
Editing /bootbank/boot.cfg to add module apple.v00
Reboot the ESXi server to install unlocker (y/N)?
```
After reboot there is error: 
![image](https://user-images.githubusercontent.com/16512337/200913965-ad4aa7b6-6282-4b18-afe9-b4d1efba92eb.png)

**Comment by DrDonk** [comment]
@S474N Can you start a new issue please as this is not related to the one documented here?

**Comment by S474N** [comment]
Done, sorry.

**Comment by DrDonk** [comment]
@S474N NP Thanks

**Comment by DrDonk** [comment]
I have a few ideas on how to track down so can you login via ssh or ESXi Console and run these commands and capture the output please?

1. `unlock` and reboot ESXI HOST
2. `check`
3. `esxcli system visorfs tardisk list`
4. `vim-cmd vmsvc/power.getallvms`
5. Select the vmid of a failing VM
6. `vim-cmd vmsvc/power.on <vmid from previous command>`
7. Let the command run for 10-30 seconds and then check powered of with next command
8. `vim-cmd vmsvc/power.off <vmid from previous command>`

Can you then collect the following files with the command output and zip up and attach to the issue please? You may want to remove any identifying info from them first.

1. Faulty VMs VMX file
2. Faulty VMs vmware.log file
3. /var/log/hostd.log
4. /var/log/vmauthd.log
5. /var/log/vmkernel.log

**Comment by dateno1** [comment]
> I have a few ideas on how to track down so can you login via ssh or ESXi Console and run these commands and capture the output please?
> 
>     1. `unlock` and reboot ESXI HOST
> 
>     2. `check`
> 
>     3. `esxcli system visorfs tardisk list`
> 
>     4. `vim-cmd vmsvc/power.getallvms`
> 
>     5. Select the vmid of a failing VM
> 
>     6. `vim-cmd vmsvc/power.on <vmid from previous command>`
> 
>     7. Let the command run for 10-30 seconds and then check powered off with next command
> 
>     8. `vim-cmd vmsvc/power.off <vmid from previous command>`
> 
> 
> Can you then collect the following files with the command output and zip up and attach to the issue please? You may want to remove any identifying info from them first.
> 
>     1. Faulty VMs VMX file
> 
>     2. Faulty VMs vmware.log file
> 
>     3. /var/log/hostd.log
> 
>     4. /var/log/vmauthd.log
> 
>     5. /var/log/vmkernel.log

[Dump.zip](https://github.com/DrDonk/esxi-unlocker/files/10090519/Dump.zip)
Logs&Command results attatched

guest has no log (screenshot attatched)

Even i can't find log with
find /vmfs -name "vmware.log*"
on ssh

**Comment by DrDonk** [comment]
@S474N Well the VM is actually crashing and dumping the process state. I can't tell why though.

Have you checked the datastore to see if it has an issue? This error has been seen when datastore has problems. I ask because I do know of someone creating and destroying hundreds of macSO vms every day and there have been no reports of this issue?

Can you zip and attach the /bin/vmx file from the unlocked system please? I can check it against my unlocked copy.

**Comment by dateno1** [comment]
> @S474N Well the VM is actually crashing and dumping the process state. I can't tell why though.
> 
> Have you checked the datastore to see if it has an issue? This error has been seen when datastore has problems. I ask because I do know of someone creating and destroying hundreds of macSO vms every day and there have been no reports of this issue?
> 
> Can you zip and attach the /bin/vmx file from the unlocked system please? I can check it against my unlocked copy.

If not unlocked all of them work well (If i was relock ESXi It Work well)

[vmx.zip](https://github.com/DrDonk/esxi-unlocker/files/10092939/vmx.zip)
Unlocked VMX attatched

**Comment by dateno1** [comment]
Now i used ESXi 8 All work well

I can boot Ventura with unlocker
