### ISSUE TITLE
Possibly incorrect permissions on files in ./tmp

### ISSUE THREAD

**Issue by GeekGoneOld** [DrDonk/esxi-unlocker#15]
ESXi 8.0 with unlocker 4.0.3 on Xeon E2378G

I first unzipped 4.0.3 into /tmp and ran the unlock.  It didn't quite work but, sorry, I can't say exactly what else I did or saw.  I eventually ran relock then unzipped to <path on datastore> and tried again (after seeing that it should be unzipped in a datastore).

Now I have a problem that it fails to unlock.  The unlock fails with the following messages:

```
Filename: ./tmp/bin/vmx
Traceback (most recent call last):
  File "./patchsmc", line 460, in <module>
    main()
  File "./patchsmc", line 445, in main
    f(filename)
  File "./patchsmc", line 213, in patchsmc
    with open(name, 'rb+') as vmx:
PermissionError: [Errno 13] Permission denied: './tmp/bin/vmx'
```
for vmx, vmx-debug, vmx-stats and libvmkctl.so

The "ls -l" of the three files in /bin are

```
-r-sr-xr-x    1 root     root      27337544 Sep 23 17:39 /bin/vmx
-r-sr-xr-x    1 root     root      36574952 Sep 23 17:39 /bin/vmx-debug
-r-sr-xr-x    1 root     root      32163592 Sep 23 17:41 /bin/vmx-stats
```
and the one in /lib64 is 

```
-r-xr-xr-x    1 root     root      11066080 Sep 23 17:43 /lib64/libvmkctl.so
```
These files are copied to ./tmp and have the same permissions there (I ran an aborted ./unlock to check)
so unless I'm missing something, the file open fails because the permissions are wrong.

What should the permissions, group and owner be in the /bin and /lib64 folders?  If they are wrong, I can chmod/chown them and try to lock again.  If they are right, how is it working for everyone else?

Please help me out.

**Comment by DrDonk** [comment]
Can you reset your system please to locked state? Then run unlock passing the -v flag. This should trace all the commands, and can yop grab the output and attach to the issue?

I have re-checked 4.0.3 on my system and no permissions errors happen.

**Comment by GeekGoneOld** [comment]
Here is the unlock -v session attached.  I'm not at all surprised that it works on your system.  I strongly suspect that my initial error (using /tmp) and the unlocking and relocking with and without rebooting and ignoring errors might have put me in a very unlikely state.  I'm sure it is easy to get out of.  Perhaps it has to do with the account I run this from (root) and the owner/group.  I really didn't do anything strongly oddball with ESXi.  I should be clear that ESXi seems to be working well.
[putty.log](https://github.com/DrDonk/esxi-unlocker/files/10329662/putty.log)

**Comment by DrDonk** [comment]
It's an odd one. On my system you can patch even if the permissions do not include w. I have modified unlock to do `chmod +w` on the files in ./tmp. Also added `ls -laR` output a few times to check permissions as the script runs.

Anyways, attached is `unlock-test.txt`. Can you copy to the esxi-unlocker folder, rename to unlock-test, and run it please (don't need -v)? You may need to `chmod +x unlock-test` to ensure it is executable.

The permissions should end up as:

* vmx files 4555/-r-sr-xr-x
* lib files 555/-r-xr-xr-x
[unlock-test.txt](https://github.com/DrDonk/esxi-unlocker/files/10332047/unlock-test.txt)

**Comment by GeekGoneOld** [comment]
As I woke up this morning, I had a eureka moment (either sleep or shower seem to be the trigger for those).  My datastore is on NFS.

I also have a small datastore that the ESXi install put on my boot drive so I tried 4.0.3 unmodified there.  It works (and my Mac booted!).  I then tried your test file on the NFS datastore and it failed just as the other one did.  I will do a few more tests so standby but I do have a workaround.

I am so very grateful to you for your dedication to this excellent tool.  Thank you very much.

**Comment by GeekGoneOld** [comment]
OK.  Stupid mistake.  I ran ./unlock, not ./unlock-test so that is why I saw no change.  unlock-test works fine even from NFS datastore.

I tried SOOO hard not to be "that guy" who skips steps, runs commands out of order etc. and then I screw up after I've figured it out!

At least we have identified that the error is that vmfs does not respect read only!!!!

Once again, many, many thanks.

**Comment by DrDonk** [comment]
That's interesting. VMFS3 ignores the permission but NFS properly uses them. I am wrapping this into the next version 4.0.4 which I'll release in the next 24 hours. You shouldn't need to re-apply the patches when 4.0.4 is out as looks like you're good to go.

Glad it's working now. Cheers.

**Comment by DrDonk** [comment]
V4.0.4 released with updates from our tests.

**Comment by GeekGoneOld** [comment]
The change you made for 4.0.4 for rw permissions in ./tmp... (8ff2cbb0a2a0eba8083b88085a6369f525b2cb4e) has a small error.  You copied the chmod code and comments and edited the comments but not the code.  Could you please change the code for the upcoming 4.0.5?

Meantime, for anyone else, either edit unlock to change the lines yourself or use a disk based datastore (not NFS).

**Comment by DrDonk** [comment]
OK I’m an idiot and missed pushing the commit to GitHub will sort out ASAP.

**Comment by GeekGoneOld** [comment]
I disagree strongly.  To me you are awesome!

Your work is VERY much appreciated.  Many, many thanks.

**Comment by DrDonk** [comment]
4.0.5 released and hope it looks right this time.

I will find sometime to setup a NFS server VM to test against.
