### ISSUE TITLE
MacOs Monterey for Esxi 6.7 work?

### ISSUE THREAD

**Issue by assistenzamerqurio** [DrDonk/esxi-unlocker#17]
Image Profile: ESXi-6.7.0-20221004001-standard
Current version of ESXi: VMware ESXi 6.7.0 build-20497097
Server: Ibm System x3650 M4 791532G

Hi, I don't know if you can help me. Unfortunately I can't update beyond version 6.7 due to a hardware problem. I would like to know if I have the possibility to use this "Unlocker" to install MacOs on my Esxi. I'd prefer to have Monterey, as the version to install, but it's not essential... Mojave or Sierra is also fine, but I can't figure out if this unlocker is also fine for version 6.x or only for version 7.x. I have the latest version of 6.7 installed... could it be some patch that won't let me get quest unlocker to work?
I summarize my questions for you, hoping you can help me

1) Does this unlocker also work for version 6.7? Can you tell me up to which version?
2) Up to which MacOs version can I install with Esxi 6.7 version?

I tried to use this unlocker, but I get these errors:

```
VMware ESXi Unlocker 4.0.5
==========================
(c) 2011-2023 David Parsons

Installing unlocker...
sh: Available: bad number
   File "./patchsmc", line 76
     print(f'File Offset : 0x{offset:08x}')
                                          ^
SyntaxError: invalid syntax
   File "./patchsmc", line 76
     print(f'File Offset : 0x{offset:08x}')
                                          ^
SyntaxError: invalid syntax
   File "./patchsmc", line 76
     print(f'File Offset : 0x{offset:08x}')
                                          ^
SyntaxError: invalid syntax
   File "./patchvmkctl", line 30
     print(f'Patch Status: {flag}')
                                 ^
SyntaxError: invalid syntax
Building apple.v00 VMTAR file...
pigz: write error code 28
pigz: abort: write error on apple.vtar.v00
mv: can't rename 'apple.vtar.v00': No such file or directory
Cleaning up tmp files...
Adding to bootbank...
File apple.v00 does not exist
Reboot the ESXi server to install unlocker (y/N)? y
Rebooting the ESXi Server
```

How can I fix?
Thanks for the work you do :)

**Comment by DrDonk** [comment]
Sorry no it won’t work on ESXi 6. I may be able to send you a set of files hand poached so long as you are not going to patch or upgrade this system.

Let me know if that is of use. I can’t guarantee it will work but happy to try for you. I need the build number of 6.7 please.

**Comment by DrDonk** [comment]
OK I don't have time to setup a 6.7 system so can you SSH onto the system and zip up these files for me and share them in this issue.

/bin/vmx
/bin/vmx-debug
/bin/vmx-stats
/lib/libvmkctl.so
/lib64/libvmkctl.so

**Comment by assistenzamerqurio** [comment]
Thank you very much for your availability
The zip file was too large to attach.
I'll send you a link to download it

https://drive.google.com/file/d/1ycWmk92C4GFeL3P6vnVXUMNJmRH_fdvP/view?usp=share_link

**Comment by DrDonk** [comment]
https://drive.google.com/file/d/1vipvy66f4a_1zW76fQMIWiZVMF3Ulou9/view?usp=sharing

To install run & reboot:

`BootModuleConfig.sh --verbose --add=apple.v00`

To uninstall run & reboot:

`BootModuleConfig.sh --verbose --remove=apple.v00`

**Comment by assistenzamerqurio** [comment]
unfortunately it seems that I can not insert the file in the folder and then launch the command. The "bin" folder has limitations

![image](https://user-images.githubusercontent.com/8253965/213703775-ca764b0a-2559-42b1-917f-6468cfd98b2c.png)

Do I need to format everything and partition the volume differently? There are no other solutions I think

**Comment by DrDonk** [comment]
Can you tell me what you are doing? You don't copy the file to /bin.

Upload the apple.v00 file to a **datastore**. There should be one available where you store your VMs. Look in /vmfs/volumes, mine is /vmfs/volumes/datastore1. Then run the command from that folder.

**Comment by Ran-Xing** [comment]
@DrDonk Would you mind showing how to pass through a macOS graphics card in ESXI? As well as the configuration of opencore, I have tried a lot of methods recently but I can’t drive the graphics card, it’s painful

**Comment by Ran-Xing** [comment]
@DrDonk I am also going to downgrade and install ESXI 6.7
ESXi-6.7.0-20210930-standard-customized

**Comment by DrDonk** [comment]
Sorry I can’t help with either. I’ve never done it and don’t have anything I can test with.

The issue tracker really is only for bugs and new feature testing.

**Comment by Ran-Xing** [comment]
@DrDonk I have installed and deployed esxi6.7
I am trying to install macOS, please leave me a message if there is anything to pay attention to

**Comment by DrDonk** [comment]
That looks OK.

**Comment by Ran-Xing** [comment]
@DrDonk It doesn't look good, esxi is really a very stable system, but it is not necessarily good, I think I have to give up using esxi as my virtualization platform, as you can see, macos is installed, to this page Stuck, I think, I guess it will be a long time before I get a chance to come back! thanks for your guidance! Happy New Year
<img width="777" alt="image" src="https://user-images.githubusercontent.com/73819467/213864066-f55f8419-7c17-48ce-abc2-63d2eea01066.png">

**Comment by DrDonk** [comment]
Well it did install which is a good thing. I'm not sure why it would be stuck at that screen though. I've not seen that before. macOS is very resource hungry in my tests, and certainly first boot before installing the VMware macOS tools is really slow.

I wish you a happy and prosperous New Year. I will be going to see the celebrations in China Town in Manchester.

**Comment by assistenzamerqurio** [comment]
Unfortunately the installation gets stuck for hours

![image](https://user-images.githubusercontent.com/8253965/214086442-23c3e21f-9c3a-4780-b2e8-8d0ea364e7ee.png)

I don't know how to go on

**Comment by DrDonk** [comment]
Have you read this https://github.com/DrDonk/unlocker/wiki/macOS-Ventura-Guests

You probably need to power down thm VM and edit the VMX file and do this:

`ethernet0.virtualDev = "e1000e"`

to

`ethernet0.virtualDev = "vmxnet3"`

**Comment by assistenzamerqurio** [comment]
Thanks so much! Now everything works perfectly.
