### ISSUE TITLE
install failed in HPE Customized Image ESXi 6.7.0 version 670.10.3.0 released on June 2018 and based on ESXi 6.7.0 Vmkernel Release Build 8169922.

### ISSUE THREAD

**Issue by jiayuwangcj** [DrDonk/esxi-unlocker#2]
Hi . 
  I just execute ./esxi-install.sh but got the result
![image](https://user-images.githubusercontent.com/24957044/46240568-2bcee180-c3dc-11e8-916e-de5296b8b97e.png)

is there something wrong I did ?

**Comment by czytcn** [comment]
It seems that ,on `esxi-build.py` on **mac** os to build unlocker.tgz, then run install.but I do not have an Apple Device!

**Comment by znanev** [comment]
@czytcn You can use Linux to build the unlocker. I tried it and it works. Or you can directly download the latest release from this link:
https://github.com/DrDonk/esxi-unlocker/releases

**Comment by DrDonk** [comment]
Have you tried the esxi-unlocker-300.tgz from the releases tab? I have the Sept HPE version of ESXi, but the June one does not seem to be available now.

**Comment by DrDonk** [comment]
I have tested against Sept version and it works correctly.

**Comment by jiayuwangcj** [comment]
I updated to Sept version to solve the problem
