### ISSUE TITLE
File unlocker.tgz does not exist

### ISSUE THREAD

**Issue by tostaky10** [DrDonk/esxi-unlocker#3]
Thanks again for this amazing tool! I get an error referencing a file that doesn't exist when executing esxi-install.sh (see below). Can you tell me what I'm doing wrong? Thanks so much.

VMware Unlocker 3.0.0
===============================
Copyright: Dave Parsons 2011-18
Installing unlocker.tgz
File unlocker.tgz does not exist

**Comment by anschluss-org** [comment]
You are trying to install from the source files which need to be built on MacOS first.

If you don't want to build yourself, you may prefer to install from the release instead:
https://github.com/DrDonk/esxi-unlocker/releases/tag/3.0.0

**Comment by tostaky10** [comment]
Thanks so much! Is there any way I can donate for your efforts? Best wishes

**Comment by DrDonk** [comment]
Or just download the release from the Releases tab.
