### ISSUE TITLE
DrDonk, after installation, some errors cause esxi fail to start

### ISSUE THREAD

**Issue by lucaskamp** [DrDonk/esxi-unlocker#7]
![1111error esxi unlocker 2022-08-06](https://user-images.githubusercontent.com/43417825/183419988-9415d864-a286-4b9a-9240-7ec329acd47b.jpg)
running the "check" and reset the system

ESXi 7.0 U3d version

**Comment by lucaskamp** [comment]
I use macos-big-sur-11.6.5-20g527 as the OSX 11 installation system, When I try to run "check", I can use IOS normally, but the system keeps restarting Finally, I chose reset esxi  : (

**Comment by nitsort** [comment]
I also had the same problem
Version: 7.0 Update 3
Image file: VMware-VMvisor-Installer-7.0.0.update03-20036589.x86_64-DellEMC_Customized-A06.iso

**Comment by DrDonk** [comment]
Odd let me find somewhere for you to upload the apple.v00 file created by the unlocker.

**Comment by lucaskamp** [comment]
I don't have more environment for test. I need a new hard disk to the experiment xD

**Comment by DrDonk** [comment]
This is why I was not keen to go back to the ESXi version as it's hard to fix the system if it goes wrong. I have an idea that the issue was due to creating a signed xz apple.v00 file. I've changed the code to not do that and stick with gzip. What I cannot quite work out is why it worked for me and not you.

My suggestion is that you setup up a nested ESXi VM to try this out is a good idea. That is how I test the code.

In the meantime I have pulled the release.

**Comment by DrDonk** [comment]
@nitsort @lucaskamp 
1. Are you using UEFI or BIOS to boot the ESXi server?
2. DO you have ESXi secure boot enabled?

**Comment by lucaskamp** [comment]
thanks so much Drdonk, esxi is really confusing,I am afraid that nested will encounter more strange problems, and I have never tried this idea,but I really appreciate to you @DrDonk

**Comment by lucaskamp** [comment]
@DrDonk  

1. I use UEFI to start the esxi server
2. I have turned off esxi secure boot

**Comment by lucaskamp** [comment]
You are only person in the world helps and tries to solve esxi Unlocker @DrDonk plz don't give up. hhh  we need you help xD

**Comment by DrDonk** [comment]
If you are really stuck you could try recovery mode.

Boot the ESXi server and press shift-r at the boot screen. Then type 'Y" to rollback to a previous installation.

**Comment by lucaskamp** [comment]
i reinstall it on another hard disk,
I need to find a new disk to test tomorrow

**Comment by DrDonk** [comment]
OK I am pushing some changes.

1. Now, the patch is not auto-loaded so system should always boot. The downside is that you will have to run the unlock command after each reboot. This makes me more comfortable with providing this patch.
2. Not patching libvmkctl.so as too problematic and is only for vCenter and I don't support this patch when ESXi is connected to vCenter.
3. If anything goes wrong just reboot the server and the patch is gone.
4. This is not the final version but if you do find a disk we can work together on testing.

**Comment by lucaskamp** [comment]
thanks alot

**Comment by DrDonk** [comment]
BTW macOS support is going from VMware products:

https://kb.vmware.com/s/article/88698

I am going to build a VM guest template that uses OpenCore to see if that can work without patches.

**Comment by lucaskamp** [comment]
I installed version 4.0.2
After installing Unlocker, I rebooted the system, and it did not report an error.
It starts normally, but fails to install MacOS again, and restarts repeatedly.

-----------[ssh install log]---------------
VMware ESXi Unlocker 4.0.2
==========================
© 2011-2022 David Parsons

Checking unlocker...
Checking VMTAR loaded...
apple.v00 not loaded
Checking vmx vSMC status...
vmx not patched
------------------------------------
![e1a47049cab559a6ccf1ec8b8d0c897](https://user-images.githubusercontent.com/43417825/184270829-a712b9a7-200c-4054-a15e-85b1152b5647.jpg)
![381442de249118009620306c0166683](https://user-images.githubusercontent.com/43417825/184270833-e554948a-73b8-4f48-bef4-2e1b8781547e.png)

**Comment by DrDonk** [comment]
OK I am finishing up a test version. So suggest uninstall the unlocker ready for the next tests.

**Comment by lucaskamp** [comment]
okay : )

**Comment by DrDonk** [comment]
Hi @lucaskamp 

Here's a test zip for you to try. Two important things:

1. You must run the unlock command each time you start the ESXi server. This means you should not get the "Purple Screen of Death" when booting as the change it not persisted.
2. So relock is really just reboot the server for the patch to be removed.

The README.md is updated on the GitHub repo.

If all goes well this will become version 4.0.2.

[esxi-unlocker-main.zip](https://github.com/DrDonk/esxi-unlocker/files/9316068/esxi-unlocker-main.zip)

**Comment by DrDonk** [comment]
And can you run the unlock command passing a -v parameter and capture the output.

`./unlock -v`

Thanks

**Comment by lucaskamp** [comment]
I'll test it later thx : D

**Comment by DrDonk** [comment]
I added you user id to the readme in the Thanks section. I hope you are OK with that?

**Comment by lucaskamp** [comment]
You are the only wise man in this great project,I just got your help

**Comment by lucaskamp** [comment]
1. Great, it works

2. I successfully installed macos12

3. After installation, OSX restarts and gets stuck in the 30% progress bar. I waited for more than 30 minutes and had to restart (in ESXi)

4. It's stuck again. I'm not sure if the hardware doesn't support it.

I keep the "check -v" log installation, if you need it I'll send it to you

I don't think you should continue to spend time on this issue, anyway it is great project @DrDonk , thank you.
maybe the hardware is not supported or driven.
![3a9a95f406d46de3d331b509d034a4f](https://user-images.githubusercontent.com/43417825/184422518-fb643b6d-ef7f-4aa4-8a1a-ebbf41e7dc5b.png)

![aff26dabe5302b60e914b9165090172](https://user-images.githubusercontent.com/43417825/184422524-75a277cb-b16b-48a2-8df9-97c3269b6e6d.png)

**Comment by DrDonk** [comment]
Can you zip up 3 files for me please?

1. the output you saved from installing the unlocker
2. the VMX file for the macOS guest
3. the vmware.log file for the macOS guest

Then attach the zip file to the issue.

You never know I may spot somethinbg.

**Comment by lucaskamp** [comment]
@DrDonk  I am trying to install a modified esxi, I need some time to reinstall the environment and help with testing

**Comment by DrDonk** [comment]
OK no problem. Appreciate the help

**Comment by lucaskamp** [comment]
Remember the sysin I mentioned to you last time?

I'm not sure whether it works. After the failure and long wait, I downloaded and installed it

It takes more time to complete the installation, which seems to be effective,


and
I found some problems. It is experiencing a second restart at 95% of the progress bar.

After many times, it seems to be stuck there

**Comment by lucaskamp** [comment]
![image](https://user-images.githubusercontent.com/43417825/184440518-5361cd8a-b16f-4444-a7b0-61e798bbe783.png)
It is effective.
There are some strange problems during installation

1. When the installation is completed, I will be prompted that other users are viewing the screen at the same time

2. Double installation time

3. Serious jamming before starting and entering the desktop

I can confirm that this version is valid and can be installed for Mac OS 12. It is integrated into the esxi installation package

**Comment by lucaskamp** [comment]
It's 4:38 am China time. If you need, I can reinstall esxi and continue to use your unlock to try and package the content you need

**Comment by DrDonk** [comment]
The vmware.log and .vmx file from your VM would still be useful. I think you are right it is something to do with your machine. It may just be a setting that needs altering in the .vmx file.

**Comment by lucaskamp** [comment]
@DrDonk please any email address : )

**Comment by DrDonk** [comment]
It's in the commit patches I've submitted. I don't want tot type it out directly.

https://github.com/DrDonk/esxi-unlocker/commit/057d941451cae58ef52eb61d0acb945805e4677d.patch

**Comment by lucaskamp** [comment]
okay delete the above conversation and I will send it to you now

**Comment by DrDonk** [comment]
Can I check one thing, this is an Intel CPU?

**Comment by lucaskamp** [comment]
yes&nbsp;CPUs x Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz&nbsp;


LucasKamp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2022年8月13日(星期六) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DrDonk/esxi-unlocker] DrDonk, after installation, some errors cause esxi fail to start (Issue #7)





 
Can I check one thing, this is an Intel CPU?
 
&mdash;

**Comment by DrDonk** [comment]
OK. So can you edit the VMX file and change the following line:

`ethernet0.virtualDev = "e1000e"`

to 

`ethernet0.virtualDev = "vmxnet3"`

Or change it via Web UI.

There was an issue reported about the Intel e1000e emulation causing lockups due to no driver shipped in macOS Monterey or Ventura.

**Comment by lucaskamp** [comment]
okay i edit it on Web UI and try again.&nbsp;


LucasKamp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2022年8月13日(星期六) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DrDonk/esxi-unlocker] DrDonk, after installation, some errors cause esxi fail to start (Issue #7)





 
OK. So can you edit the VMX file and change the following line:
 
ethernet0.virtualDev = "e1000e"
 
to
 
ethernet0.virtualDev = "vmxnet3"
 
Or change it via Web UI.
 
There was an issue reported about the Intel e1000e emulation causing lockups due to no driver shipped in macOS Monterey or Ventura.
 
&mdash;

**Comment by lucaskamp** [comment]
starting 30% of the progress bar is stuck again
&nbsp;


LucasKamp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2022年8月13日(星期六) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DrDonk/esxi-unlocker] DrDonk, after installation, some errors cause esxi fail to start (Issue #7)





 
OK. So can you edit the VMX file and change the following line:
 
ethernet0.virtualDev = "e1000e"
 
to
 
ethernet0.virtualDev = "vmxnet3"
 
Or change it via Web UI.
 
There was an issue reported about the Intel e1000e emulation causing lockups due to no driver shipped in macOS Monterey or Ventura.
 
&mdash;

**Comment by lucaskamp** [comment]
I found an interesting thing. When I tried to email you, they were automatically posted to GitHub.
so I must to clean up any time. hhhh XD
&nbsp;


LucasKamp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2022年8月13日(星期六) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DrDonk/esxi-unlocker] DrDonk, after installation, some errors cause esxi fail to start (Issue #7)





 
OK. So can you edit the VMX file and change the following line:
 
ethernet0.virtualDev = "e1000e"
 
to
 
ethernet0.virtualDev = "vmxnet3"
 
Or change it via Web UI.
 
There was an issue reported about the Intel e1000e emulation causing lockups due to no driver shipped in macOS Monterey or Ventura.
 
&mdash;

**Comment by DrDonk** [comment]
Well I'm now sort of out of ideas. Can you try booting the guest in verbose mode and see if there are any macOS errors reported? Press command-v when booting.

**Comment by lucaskamp** [comment]
I use vim-cmd to start, but I'm not sure how to use the -v command to enter verbose mode

**Comment by lucaskamp** [comment]
I think it takes too much time. maybe it's wise to wait for the next version of VM or like you said, use nesting : )

**Comment by DrDonk** [comment]
OK. sorry we didn't get this sorted. I'll do some checks myself.

Shall I close this issue, and you can open a new one if new info becomes available?

**Comment by lucaskamp** [comment]
Thanks to Dr Donk, through your unremitting efforts, at least it has achieved some success. I will try other environments, if conditions permit, You can close it. We can contact you by mail at any time. Thank you for your help

**Comment by DrDonk** [comment]
Yes feel free to email me if you get further or want to pass and idea past me.
