### ISSUE TITLE
Fix for  VMWare Esxi 7U3g

### ISSUE THREAD

**Issue by Systm21** [DrDonk/esxi-unlocker#8]
Hello @DrDonk,
is it possible to fix the unlocker for the last Version of ESXi or for U3 mainly? On Workstation it works, but on Esxi it boots, but get stuck on the half. 

greetings

**Comment by DrDonk** [comment]
You can grab the code in the repo and try it. I had to make changes to how it is run auto avoid crashing ESXi. You will need to unlock after every reboot of the ESXi server.

Make sure you read the readme.md file.

I am in the UK and will be taking time away from tech for a few days after the news here. Please leave updates here and I will get back to you in a few days.

**Comment by DrDonk** [comment]
I have tested it and this should work on 7U3g.

**Comment by alclonky** [comment]
I think this issue can be closed, 
Version 4.0.3 works with ESXi 7.0u3g

**Comment by DrDonk** [comment]
Yes we've both tested it on that version, so will close.
