### ISSUE TITLE
Support for vcenter

### ISSUE THREAD

**Issue by alclonky** [DrDonk/esxi-unlocker#9]
Any chance to Support esxi hosts connected to vcenter?
I tried the unlocker and the VM starts fine on the esx host itself but if I start the same VM over vCenter I get an error.

Thx a lot for your work!

**Comment by DrDonk** [comment]
I removed the patch for this as it made the ESXi host unstable, and so I am only supporting ESXi as a standalone server.

Sorry about that but I do not want to risk ESXi hosts causing problems in a vCenter setup.

**Comment by DrDonk** [comment]
I am wondering if there is a way to modify the XML response by a web proxy to set  SMCpresent flag to vCenter?

**Comment by DrDonk** [comment]
I have done some testing and I think I may have been a bit hasty and could have something for ESXi 7. Issues were reported in the ESXi 6 days. I have a simple way to patch ESXi host whilst it is running but does involve stopping and starting the hostd process which hosts ESXi web service used by vCenter.

Would you be happy to test something out for me please? I have retired from software development and really only have access to ESXi these days. I still need to double check the work so would be a standalone test ready in a couple of hours.

**Comment by DrDonk** [comment]
@alclonky Can you give the new 4.0.3 release a try please? I have added back the patch for the flag vCenter looks for, and the patch is loaded automatically at boot to ensure the hostd service loads the patch early in startup.

**Comment by alclonky** [comment]
you are the best. 
tried on the first esxi node and can boot the VM via vCenter Server now!
will update the Server from 7u3c to 7u3g and test again. 
On Monday I can also test with  my lab load (around 100 mac VMs created and removed per day for testing)

**Comment by alclonky** [comment]
Also works with 7.0u3g

**Comment by DrDonk** [comment]
Cool. Just need to make sure you remove and unlock if you do an upgrade. See the troubleshooting notes for so hints.

**Comment by alclonky** [comment]
So far everything runs as expected.
3 ESXi hosts 7.0u3g with vCenter.
